"""added todo_time column

Revision ID: d969f5743e1a
Revises: e51da60c0236
Create Date: 2024-12-24 13:12:19.516088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd969f5743e1a'
down_revision: Union[str, None] = 'e51da60c0236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('todo_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'todo_time')
    # ### end Alembic commands ###
